/* Originally generated by Payload — same segment normalization as page.tsx */
import type { Metadata } from "next";

import config from "@/payload.config";
import { normalizeAdminRouteSegments } from "@/lib/adminSegments";
import { importMap } from "../importMap.js";
import { NotFoundPage, generatePageMetadata } from "@payloadcms/next/views";

type Args = {
  params: Promise<{
    segments?: string | string[];
  }>;
  searchParams: Promise<{
    [key: string]: string | string[];
  }>;
};

function normalizedParams(params: Args["params"]) {
  return (async () => {
    const p = await params;
    return { segments: normalizeAdminRouteSegments(p.segments) };
  })();
}

export const generateMetadata = ({ params, searchParams }: Args): Promise<Metadata> =>
  generatePageMetadata({ config, params: normalizedParams(params), searchParams });

const NotFound = ({ params, searchParams }: Args) =>
  NotFoundPage({ config, importMap, params: normalizedParams(params), searchParams });

export default NotFound;
