/* Originally generated by Payload — extended so Next.js segment params match Payload.
 * (Optional catch-all may yield `segments` as a string; Payload expects string[].) */
import type { Metadata } from "next";

import config from "@/payload.config";
import { normalizeAdminRouteSegments } from "@/lib/adminSegments";
import { importMap } from "../importMap.js";
import { RootPage, generatePageMetadata } from "@payloadcms/next/views";

type Args = {
  params: Promise<{
    segments?: string | string[];
  }>;
  searchParams: Promise<{
    [key: string]: string | string[];
  }>;
};

function normalizedParams(params: Args["params"]) {
  return (async () => {
    const p = await params;
    return { segments: normalizeAdminRouteSegments(p.segments) };
  })();
}

export const generateMetadata = ({ params, searchParams }: Args): Promise<Metadata> =>
  generatePageMetadata({ config, params: normalizedParams(params), searchParams });

const Page = ({ params, searchParams }: Args) =>
  RootPage({ config, importMap, params: normalizedParams(params), searchParams });

export default Page;
